# Generated by Django 6.0 on 2026-02-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_profile_account_number_profile_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='bank_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
