"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-khpz1n-)d6+cb3mt%6&psf802(#2^8ndqixqu2snvh2l3k@zak')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'

# Allowed hosts - configured via environment variable or default to all hosts
# For production, replace '*' with your specific domain/IP for better security
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',') if os.environ.get('DJANGO_ALLOWED_HOSTS') else ['*']



# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    'wallet.apps.WalletConfig',
    'api',
    'tournaments',
    'payments',
    "channels",
    "chat",
    "hostpartner",
]


MIDDLEWARE = [
     "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if not DEBUG:
    MIDDLEWARE.insert(2, 'whitenoise.middleware.WhiteNoiseMiddleware')

# CORS Configuration
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
    CORS_ALLOW_CREDENTIALS = True
    # CSRF trusted origins for production
    CSRF_TRUSTED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')



ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = "backend.asgi.application"

# Channel Layers for WebSockets
# Use Redis in production, InMemory for development
REDIS_URL = os.environ.get('REDIS_URL', None)

if REDIS_URL:
    # Production: Use Redis for channel layers
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    # Development: Use in-memory channel layer
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }




# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases



# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field



# Superbase - prostgresql database configuration

import dj_database_url
from decouple import config

# Keep the legacy DEBUG variable as a fallback, while giving DJANGO_DEBUG
# precedence so local and production configurations use the same setting.
DEBUG = config(
    'DJANGO_DEBUG',
    default=config('DEBUG', default=DEBUG, cast=bool),
    cast=bool,
)

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL'),
        conn_max_age=600,
        ssl_require=True,
    )
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
if DEBUG:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

from datetime import timedelta

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}

# PhonePe Standard Checkout (UPI only)
PHONEPE_CLIENT_ID = (
    os.environ.get("PHONEPE_CLIENT_ID") or os.environ.get("Client Id", "")
).strip()
PHONEPE_CLIENT_SECRET = (
    os.environ.get("PHONEPE_CLIENT_SECRET") or os.environ.get("Client Secret", "")
).strip()
PHONEPE_CLIENT_VERSION = (
    os.environ.get("PHONEPE_CLIENT_VERSION")
    or os.environ.get("Client Version")
    or "1"
).strip()
PHONEPE_ENV = os.environ.get("PHONEPE_ENV", "SANDBOX").upper()
PHONEPE_REDIRECT_URL = os.environ.get(
    "PHONEPE_REDIRECT_URL",
    f"{os.environ.get('FRONTEND_URL', 'http://localhost:5173')}/wallet/add-money",
)

# PhonePe Payouts requires payout product access. Keep its credentials and
# endpoint separate from Standard Checkout credentials.
PHONEPE_PAYOUT_CLIENT_ID = os.environ.get("PHONEPE_PAYOUT_CLIENT_ID", PHONEPE_CLIENT_ID).strip()
PHONEPE_PAYOUT_CLIENT_SECRET = os.environ.get("PHONEPE_PAYOUT_CLIENT_SECRET", PHONEPE_CLIENT_SECRET).strip()
PHONEPE_PAYOUT_CLIENT_VERSION = os.environ.get("PHONEPE_PAYOUT_CLIENT_VERSION", PHONEPE_CLIENT_VERSION).strip()
PHONEPE_PAYOUT_URL = os.environ.get("PHONEPE_PAYOUT_URL", "").strip()
PHONEPE_PAYOUT_FEE = os.environ.get("PHONEPE_PAYOUT_FEE", "5.00")
PHONEPE_PAYOUT_GST_RATE = os.environ.get("PHONEPE_PAYOUT_GST_RATE", "18.00")
PHONEPE_PAYOUT_TEST_MODE = (
    DEBUG and os.environ.get("PHONEPE_PAYOUT_TEST_MODE", "False").lower() == "true"
)
PHONEPE_PAYMENT_FEE = os.environ.get("PHONEPE_PAYMENT_FEE", "5.00")
PHONEPE_PAYMENT_GST_RATE = os.environ.get("PHONEPE_PAYMENT_GST_RATE", "18.00")

# JWT Settings
# The existing SIMPLE_JWT definition is replaced with this more comprehensive one.
# The timedelta import is already present at the top of the REST_FRAMEWORK section.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=5),  # 5 hours
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

CSRF_TRUSTED_ORIGINS = [
    "https://tournamentarena.bookontime.shop",
    "https://www.tournamentarena.bookontime.shop",
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

RESEND_API_KEY = os.environ.get("RESEND_API_KEY")
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:5173")
RESEND_FROM_EMAIL = os.environ.get("RESEND_FROM_EMAIL", "onboarding@resend.dev")