# Generated by Django 6.0 on 2025-12-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text='Last date/time to register', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Tournament start date/time', null=True),
        ),
    ]
