# Generated by Django 6.0 on 2025-12-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_registration_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prizedistribution',
            name='prize_percentage',
        ),
        migrations.AddField(
            model_name='prizedistribution',
            name='prize_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed prize amount', max_digits=10),
        ),
    ]
