# Generated by Django 6.0 on 2025-12-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_remove_prizedistribution_prize_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_participants',
            field=models.IntegerField(default=100, help_text='Maximum total participants allowed'),
        ),
    ]
