# Generated by Django 6.0 on 2025-12-20 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournament_max_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tournament',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='tournaments.tournament'),
        ),
    ]
