# Generated by Django 6.0 on 2026-02-06 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_room_tournament'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='roomparticipant',
            options={'ordering': ['team_name', 'joined_at']},
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(default=1, help_text='Room number for this tournament'),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='game_id_used',
            field=models.CharField(blank=True, help_text='Game ID used for this room', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='team_name',
            field=models.CharField(blank=True, help_text='Team name for duo/squad modes', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='tournaments.tournament'),
        ),
    ]
