# Generated by Django 5.1.6 on 2026-02-06 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_room_options_alter_roomparticipant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roomparticipant',
            options={},
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='roomparticipant',
            name='game_id_used',
        ),
        migrations.RemoveField(
            model_name='roomparticipant',
            name='team_name',
        ),
        migrations.AlterField(
            model_name='room',
            name='tournament',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='tournaments.tournament'),
        ),
    ]
