# Generated by Django 5.1.6 on 2026-02-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_alter_room_options_alter_roomparticipant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='payment_type',
            field=models.CharField(choices=[('leader_pays_all', 'Leader Pays All'), ('split_equally', 'Split Equally')], default='split_equally', help_text='How team payment is handled', max_length=20),
        ),
    ]
