# Generated by Django 5.2.17 on 2026-09-11 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostpartner', '0001_initial'),
        ('tournaments', '0008_room_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='custom_player_count',
            field=models.IntegerField(default=0, help_text='Used for BR / custom long tournaments'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='host_partner_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='hostpartner.hostpartnerrequest'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('one_vs_one', 'One vs One'), ('br', 'BR / Long Tournament')], default='one_vs_one', max_length=20),
        ),
    ]
