# Generated by Django 5.2.17 on 2026-09-21 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_tournament_creator_prize_pool_funded'),
        ('tournaments', '0010_tournamenteearning'),
    ]

    operations = [
    ]
