# Generated by Django 5.2.17 on 2026-09-21 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_merge_20260921_0058'),
        ('tournaments', '0011_tournamenttimeslot'),
    ]

    operations = [
    ]
